services:
    waaz.fedex_plugin.form.type.fedex_shipping_gateway:
        class: Waaz\SyliusFedexPlugin\Form\Type\ShippingGatewayType
        tags:
            - { name: bitbag.shipping_gateway_configuration_type, type: 'fedex', label: "FedEx" }

    waaz.fedex_plugin.api.client:
        class: Waaz\SyliusFedexPlugin\Api\FedexClient
        arguments:
            - '@http_client'
            - '@?cache.app'

    waaz.fedex_plugin.factory.shipper:
        class: Waaz\SyliusFedexPlugin\Factory\ShipperFactory

    waaz.fedex_plugin.factory.recipient:
        class: Waaz\SyliusFedexPlugin\Factory\RecipientFactory

    waaz.fedex_plugin.factory.package_line_items:
        class: Waaz\SyliusFedexPlugin\Factory\PackageLineItemsFactory

    waaz.fedex_plugin.factory.shipment_payload:
        class: Waaz\SyliusFedexPlugin\Factory\ShipmentPayloadFactory
        arguments:
            - '@waaz.fedex_plugin.factory.shipper'
            - '@waaz.fedex_plugin.factory.recipient'
            - '@waaz.fedex_plugin.factory.package_line_items'

    waaz.fedex_plugin.api.shipping_label_fetcher:
        class: Waaz\SyliusFedexPlugin\Api\ShippingLabelFetcher
        arguments:
            - '@request_stack'
            - '@waaz.fedex_plugin.api.client'
            - '@waaz.fedex_plugin.factory.shipment_payload'
            - '%waaz_sylius_fedex_plugin.weight_unit%'

    waaz.fedex_plugin.event_listener.fedex_shipping_export:
        class: Waaz\SyliusFedexPlugin\EventListener\ShippingExportEventListener
        arguments:
            - '@filesystem'
            - '@bitbag.repository.shipping_export'
            - '%bitbag.shipping_labels_path%'
            - '@waaz.fedex_plugin.api.shipping_label_fetcher'
        tags:
            - { name: kernel.event_listener, event: 'bitbag.shipping_export.export_shipment', method: exportShipment }

    waaz.fedex_plugin.provider.fedex:
        class: Waaz\SyliusFedexPlugin\Provider\FedexProvider
        arguments:
            - '@waaz.fedex_plugin.api.client'
        tags:
            - { name: 'setono_sylius_pickup_point.provider', code: fedex, label: 'FedEx' }

    # Service Aliases
    Waaz\SyliusFedexPlugin\Api\FedexClientInterface: '@waaz.fedex_plugin.api.client'
    Waaz\SyliusFedexPlugin\Api\ShippingLabelFetcherInterface: '@waaz.fedex_plugin.api.shipping_label_fetcher'
    Waaz\SyliusFedexPlugin\Factory\ShipperFactoryInterface: '@waaz.fedex_plugin.factory.shipper'
    Waaz\SyliusFedexPlugin\Factory\RecipientFactoryInterface: '@waaz.fedex_plugin.factory.recipient'
    Waaz\SyliusFedexPlugin\Factory\PackageLineItemsFactoryInterface: '@waaz.fedex_plugin.factory.package_line_items'
    Waaz\SyliusFedexPlugin\Factory\ShipmentPayloadFactoryInterface: '@waaz.fedex_plugin.factory.shipment_payload'
    Waaz\SyliusFedexPlugin\Provider\FedexProvider: '@waaz.fedex_plugin.provider.fedex'
